### PR TITLE
added .devcontainer config

### PR DESCRIPTION
**Pull request by behrica**
allows to start a devcontainer with all dependencies ( clojure, R + packages) installed.

can be used with vscode or 
Emacs (using the  [devpod](https://devpod.sh/)   tool)

A simple `devpod up .` starts a devconatiner to which you can ssh to.

### CODE REVIEW

**Comment by behrica** [comment]
can this be merged ?

**Comment by behrica** [comment]
I will remove te "launchpad" related files, not sure why there went into the PR

**Comment by genmeblog** [comment]
Should I merge it at this stage? Or any other changes are comming?

**Review by genmeblog — APPROVED** [review]
For me it's ok. Actually I won't verify this though assuming everything works as intended (I don't use docker).

**Pull request merged**
