### PR TITLE
first attempt of help function

### PR DESCRIPTION
**Pull request by behrica**

### CODE REVIEW

**Comment by behrica** [comment]
@daslu 
any feedback on this ?

**Comment by daslu** [comment]
@behrica I'll look, thanks.

Sorry for not responding earlier.

**Comment by genmeblog** [comment]
I will merge this in BETA20 (I'll release it soon)

**Comment by behrica** [comment]
Just a reminder about this PR.

**Comment by daslu** [comment]
Thanks, @behrica, sorry it was somehow left out.
I will look soon.

**Comment by genmeblog** [comment]
OMG, I forgot about it. Sorry @behrica. I've verified it already @daslu and will merge it and release (what I promised last time).

**Pull request merged**
