### PR TITLE
:arglists tag added to required R functions

### PR DESCRIPTION
**Pull request by genmeblog**
Solves #22 and #8 
Still no proper meta tags for generic functions.

### CODE REVIEW

**Comment by genmeblog** [comment]
I'va also added warning when require fails due to wrong package name (as it is in plotting)

**Comment by genmeblog** [comment]
Something is wrong now, please wait for fix

**Comment by genmeblog** [comment]
Ok, now seems to work.

Crucial change in refering R names containing dot. Refering operates on clojure symbol names. To import eg. `summary-default` previously one had to:

```clojure
(require-r '[base :refer [summary.default]])
```

Now it's consistent with what is created on Clojure side

```clojure
(require-r '[base :refer [summary-default]])
```

**Comment by daslu** [comment]
@genmeblog looks wonderful!

Some comments:

1. It seems that the `require-r` function was removed. A mistake?

2. At some places in the code, we use the old way of `refer`ing symbols with dots. For example, here:
https://github.com/scicloj/clojisr/blob/master/src/clojisr/v1/applications/plotting.clj#L8
https://github.com/scicloj/clojisr/blob/master/test/clojisr/v1/titanic0_test.clj#L49
This breaks.
Maybe it is better to allow for the old way too? That is, maybe both `(require-r '[base :refer [summary.default]])` and `(require-r '[base :refer [summary-default]])` should be allowed?
What do you think?

Tomorrow I'll do some tests, and then merge.

**Comment by genmeblog** [comment]
Oh... How could I remove it? Let me make a fix. 

Regarding the second issue, I opt for one version: you require a name a this name as created. Names with dots are not possible so I would remove this option. Also, it's easier in implementation where `select-keys` are used. On the other side you have to remember this inconsistency with R. Let me know what you think. I can fix missed imports or revert and add dash version in refering.

**Comment by daslu** [comment]
> I opt for one version: you require a name a this name as created. 

Sounds good!

**Comment by daslu** [comment]
@genmeblog this is great.

Do you remember some functions that you used to develop and check your arglists logic?
I'll use that to for tests, so that I do not break anything when changing the logic.

I'll try to add support for [primitive functions](http://adv-r.had.co.nz/Functions.html), where `formals`[behaves differently](https://stackoverflow.com/a/25978487/1723677).

I'll also try to see how hard it is to support python functions brought by [reticulate](https://rstudio.github.io/reticulate/). 

(edit: fixed link)

**Pull request merged**
